spring:
  application:
    name: demo
    
# JDBCの接続設定
dbcp2.jdbc:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/moviedb?characterEncoding=UTF-8
  username: root1
  password: password
  initial-size: 1
  max-idle: 3
  min-idle: 1

# mybatisの設定
mybatis:
  mapper-locations: classpath:com/example/demo/repository/mybatis/*.xml